import Editor from '@monaco-editor/react'
import ReactMarkdown from 'react-markdown'
import { Play, Pencil, Trash2, Copy, Check, FileText, Code, BookOpen } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from '@/components/ui/sheet'
import type { Skill } from '@/api/skills'

interface SkillDetailProps {
  skill: Skill | null
  isOpen: boolean
  onClose: () => void
  onEdit: () => void
  onDelete: () => void
  onExecute: () => void
}

export function SkillDetail({
  skill,
  isOpen,
  onClose,
  onEdit,
  onDelete,
  onExecute,
}: SkillDetailProps) {
  const [copied, setCopied] = useState(false)
  const [activeTab, setActiveTab] = useState('implementation')

  const handleCopy = async () => {
    if (skill?.body) {
      await navigator.clipboard.writeText(skill.body)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  // Generate documentation if not present
  const getDocumentation = (skill: Skill): string => {
    if (skill.documentation) return skill.documentation
    
    // Generate basic documentation
    let md = `# ${skill.name}\n\n`
    if (skill.version) md += `**Version:** ${skill.version}\n\n`
    md += `## Description\n\n${skill.description || 'No description provided.'}\n\n`
    
    if (skill.parameters && skill.parameters.length > 0) {
      md += `## Parameters\n\n`
      md += `| Name | Type | Required | Default | Description |\n`
      md += `|------|------|----------|---------|-------------|\n`
      for (const p of skill.parameters) {
        md += `| \`${p.name}\` | \`${p.type || 'STRING'}\` | ${p.required !== false ? 'Yes' : 'No'} | ${p.default !== undefined ? `\`${p.default}\`` : '-'} | ${p.description || '-'} |\n`
      }
      md += '\n'
    }
    
    if (skill.return_type) {
      md += `## Returns\n\n**Type:** \`${skill.return_type}\`\n\n`
    }
    
    md += `## Usage\n\n`
    md += "```sql\nCALL " + skill.name + "();\n```\n\n"
    
    md += `---\n\n*Generated by Moltler Skills Manager*\n`
    
    return md
  }

  if (!skill) return null

  return (
    <Sheet open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <SheetContent side="right" className="w-full sm:max-w-2xl flex flex-col">
        <SheetHeader>
          <div className="flex items-center justify-between">
            <SheetTitle className="flex items-center gap-2">
              {skill.name}
              <Badge variant={skill.type === 'PROCEDURE' ? 'default' : skill.type === 'SKILL' ? 'success' : 'secondary'}>
                {skill.type}
              </Badge>
            </SheetTitle>
          </div>
          <SheetDescription>
            {skill.description || 'No description'}
          </SheetDescription>
        </SheetHeader>

        <div className="flex-1 flex flex-col gap-4 overflow-hidden py-4">
          {/* Parameters (always visible) */}
          {skill.parameters && skill.parameters.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-sm font-medium">Parameters</h4>
              <div className="flex flex-wrap gap-2">
                {skill.parameters.map((param, idx) => (
                  <Badge key={idx} variant="outline" className="font-mono">
                    {param.mode && <span className="text-muted-foreground mr-1">{param.mode}</span>}
                    {param.name}: {param.type}
                    {param.default !== undefined && <span className="text-muted-foreground ml-1">= {String(param.default)}</span>}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          {/* Tabs for Implementation and Documentation */}
          <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col overflow-hidden">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="implementation" className="flex items-center gap-2">
                <Code className="h-4 w-4" />
                Implementation
              </TabsTrigger>
              <TabsTrigger value="documentation" className="flex items-center gap-2">
                <BookOpen className="h-4 w-4" />
                Documentation
              </TabsTrigger>
            </TabsList>

            {/* Implementation Tab */}
            <TabsContent value="implementation" className="flex-1 flex flex-col overflow-hidden mt-4">
              <div className="flex items-center justify-between mb-2">
                <h4 className="text-sm font-medium text-muted-foreground">Source Code</h4>
                <Button variant="ghost" size="sm" onClick={handleCopy}>
                  {copied ? (
                    <>
                      <Check className="mr-2 h-4 w-4 text-green-500" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="mr-2 h-4 w-4" />
                      Copy
                    </>
                  )}
                </Button>
              </div>
              <div className="flex-1 border rounded-md overflow-hidden min-h-[300px]">
                <Editor
                  height="100%"
                  defaultLanguage="sql"
                  value={skill.body}
                  theme="vs-dark"
                  options={{
                    readOnly: true,
                    minimap: { enabled: false },
                    fontSize: 13,
                    lineNumbers: 'on',
                    scrollBeyondLastLine: false,
                    automaticLayout: true,
                    wordWrap: 'on',
                  }}
                />
              </div>
            </TabsContent>

            {/* Documentation Tab */}
            <TabsContent value="documentation" className="flex-1 overflow-auto mt-4">
              <div className="prose prose-sm dark:prose-invert max-w-none p-4 bg-muted/30 rounded-lg border">
                <ReactMarkdown
                  components={{
                    // Custom styling for markdown elements
                    h1: ({ children }) => <h1 className="text-2xl font-bold mb-4">{children}</h1>,
                    h2: ({ children }) => <h2 className="text-xl font-semibold mt-6 mb-3 border-b pb-2">{children}</h2>,
                    h3: ({ children }) => <h3 className="text-lg font-medium mt-4 mb-2">{children}</h3>,
                    p: ({ children }) => <p className="mb-3 leading-relaxed">{children}</p>,
                    code: ({ className, children }) => {
                      const isBlock = className?.includes('language-')
                      if (isBlock) {
                        return (
                          <pre className="bg-zinc-900 text-zinc-100 p-4 rounded-lg overflow-x-auto my-4">
                            <code>{children}</code>
                          </pre>
                        )
                      }
                      return <code className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">{children}</code>
                    },
                    table: ({ children }) => (
                      <div className="overflow-x-auto my-4">
                        <table className="min-w-full border-collapse border border-border">{children}</table>
                      </div>
                    ),
                    th: ({ children }) => <th className="border border-border bg-muted px-3 py-2 text-left font-medium">{children}</th>,
                    td: ({ children }) => <td className="border border-border px-3 py-2">{children}</td>,
                    ul: ({ children }) => <ul className="list-disc pl-6 mb-3">{children}</ul>,
                    ol: ({ children }) => <ol className="list-decimal pl-6 mb-3">{children}</ol>,
                    li: ({ children }) => <li className="mb-1">{children}</li>,
                    hr: () => <hr className="my-6 border-border" />,
                    img: ({ src, alt }) => (
                      <img src={src} alt={alt} className="inline-block h-5 mr-1" />
                    ),
                  }}
                >
                  {getDocumentation(skill)}
                </ReactMarkdown>
              </div>
            </TabsContent>
          </Tabs>

          {/* Metadata */}
          {(skill.created_at || skill.updated_at || skill.author || skill.version) && (
            <div className="text-xs text-muted-foreground space-y-1 border-t pt-3">
              <div className="flex flex-wrap gap-4">
                {skill.version && <span>Version: {skill.version}</span>}
                {skill.author && <span>Author: {skill.author}</span>}
                {skill.created_at && <span>Created: {new Date(skill.created_at).toLocaleString()}</span>}
                {skill.updated_at && <span>Updated: {new Date(skill.updated_at).toLocaleString()}</span>}
              </div>
              {skill.tags && skill.tags.length > 0 && (
                <div className="flex gap-1 mt-2">
                  {skill.tags.map((tag, idx) => (
                    <Badge key={idx} variant="secondary" className="text-xs">
                      {tag}
                    </Badge>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex items-center justify-between pt-4 border-t">
          <Button
            variant="destructive"
            size="sm"
            onClick={onDelete}
          >
            <Trash2 className="mr-2 h-4 w-4" />
            Delete
          </Button>
          <div className="flex gap-2">
            <Button variant="outline" onClick={onExecute}>
              <Play className="mr-2 h-4 w-4" />
              Execute
            </Button>
            <Button onClick={onEdit}>
              <Pencil className="mr-2 h-4 w-4" />
              Edit
            </Button>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  )
}
